apiVersion: apps/v1
kind: Deployment
metadata:
  name: testforward
spec:
  replicas: 3										# 这里用三个副本
  selector:
    matchLabels:
      run: testforward
  template:
    metadata:
      labels:
        run: testforward
    spec:
      containers:
      - image: mark2first/testtomcatcz:v1					# 这里以之前构建的镜像为例
        name: testforward
        ports:
        - containerPort: 8080
          protocol: TCP